# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'CISTEC-INNOVATION-LAB (18179fd4-342d-4db2-935a-e496aafce30c)'
    subscriptionId: '18179fd4-342d-4db2-935a-e496aafce30c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'GRA'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/dsaenzgithub/WEbAppARM.git'
    deploymentMode: 'Incremental'